pub const ERR_DISTRIBUTION_PAUSED: &str = "LP0003_DISTRIBUTION_PAUSED";
pub const ERR_NULLIFIER_ALREADY_CLAIMED: &str = "LP0003_NULLIFIER_ALREADY_CLAIMED";
pub const ERR_INVALID_MERKLE_PROOF: &str = "LP0003_INVALID_MERKLE_PROOF";
pub const ERR_ALLOCATION_MISMATCH: &str = "LP0003_ALLOCATION_MISMATCH";
